### ISSUE TITLE
Implement camunda:jobPriority

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-bpmn-moddle#11]

**Comment by ThorbenLindhauer** [comment]
You can have the job priority attribute also on events and gateways. Basically anywhere where you can set camunda:asyncBefore and asyncAfter.

Engine test suite example: https://github.com/camunda/camunda-bpm-platform/blob/master/qa/integration-tests-engine/src/test/resources/org/camunda/bpm/integrationtest/jobexecutor/JobPrioritizationTest.intermediateMessage.bpmn20.xml

**Comment by ThorbenLindhauer** [comment]
And the attribute type should be String since it can also hold expressions.

**Comment by nikku** [comment]
Great catch. Fixed and released as `v0.2.1`.

**Comment by ThorbenLindhauer** [comment]
Thank you :)
