### ISSUE TITLE
I can configure external tasks for all ServiceTaskLike elements

### ISSUE THREAD

**Issue by meyerdan** [camunda/camunda-bpmn-moddle#25]
Depends on https://app.camunda.com/jira/browse/CAM-4690

**Comment by ThorbenLindhauer** [comment]
CAM-4690 is done and should be part of future SNAPSHOT builds.

**Comment by nikku** [comment]
This is a minor release, once we got that in. We should create a `external task capable` entity first and make sure to just update it as part of the release. That allows us to base the properties panel on that type and (eventually) define compatibility just through different camunda-bpmn-moddle versions.

**Comment by romansmirnov** [comment]
I also added some test cases in the properties panel (see https://github.com/bpmn-io/bpmn-js-properties-panel/commit/9f919a3d0ade0bc2af642e22264fbaab0ec9d7b1).

@pedesen Once you have finished the review, could you please show me how to release it?
