### ISSUE TITLE
Set 'resultList' as default value for the attribute 'camunda:mapDecisionResult'

### ISSUE THREAD

**Issue by romansmirnov** [camunda/camunda-bpmn-moddle#27]

**Comment by ingorichtsmeier** [comment]
from my personal experience, `singleEntry` is the setting that I needed for most of my decision tables right now.

**Comment by nikku** [comment]
@ingorichtsmeier The question is not "what do you need" but what is the default according to the DMN standard.

@romansmirnov Result list is correct according to the standard?

**Comment by nikku** [comment]
Ahh, sorry according to the engine, if we are talking about the Camunda extension.

**Comment by ingorichtsmeier** [comment]
Yes, it's a camunda extension. Mosty you model one output column which you give back as a single process variable.

**Comment by menski** [comment]
The default in the engine is `resultList`.

**Comment by nikku** [comment]
All right. So the behavior we implemented is correct until we change the default behavior of the engine.
