### ISSUE TITLE
Task priority is of type Integer instead of type String

### ISSUE THREAD

**Issue by meyerdan** [camunda/camunda-bpmn-moddle#31]
The task priority is currently defined as integer.
It should be defined as String since it can be an expression.

https://docs.camunda.org/manual/7.4/reference/bpmn20/custom-extensions/extension-attributes/#priority

**Comment by gimbel** [comment]
we shall fix this before releasing PP07 right?

https://github.com/bpmn-io/bpmn-js-properties-panel/issues/176
