### ISSUE TITLE
Missing elements from Camunda Extension Elements that are "allowedIn"

### ISSUE THREAD

**Issue by ricardomatias** [camunda/camunda-bpmn-moddle#35]
- [x] connector -> Message Event Definition of Message Intermediate Throwing Event or Message End Event

- [x] executionListener -> Embedded Subprocess, Event SubProcess, Transaction SubProcess (type SubProcess)

- [x] failedJobRetryTimeCycle -> bpmn:TimerEventDefinition (for  Timer Start Event, Timer Intermediate Catching Event, Timer Boundary Event), SignalEventDefinition, MultiInstanceLoopCharacteristics

- [x] field -> Message Event Definition of Message Intermediate Throwing Event or Message End Event

**Comment by nikku** [comment]
Missing: Document the JavaScript pieces needed for property cloning in the `README.md`.
